package io;

public enum MessageKey {
    PROMPT_DATES,
    PROMPT_DATA_FORMAT_CHOICE,
    PROMPT_LOCALE_CHOICE,
    PROMPT_MAIN_MENU_CHOICE,
    DISPLAY_RANDOM_MOVIE,
    PROMPT_ACTOR_FIRST_NAME,
    PROMPT_ACTOR_LAST_NAME,
    EXIT_PROGRAM,
    SELECT_START_YEAR,
    SELECT_END_YEAR,
    INVALID_YEAR_ORDER,
    ENTER_VALID_INT,
    ENTER_VALID_STRING,
    SELECT_DATA_FORMAT,
    INVALID_MENU_CHOICE,
    YOUR_CHOICE,
    INVALID_CHOICE_TEMPLATE,
    NO_MOVIES_FOUND_IN_RANGE_TEMPLATE,
    MOVIES_BY_ACTOR_NOT_FOUND_TEMPLATE,
    CHOOSE_YOUR_LANGUAGE,
    PROMPT_SEARCH_ACTOR,
    INVALID_LOCALE_CHOICE
}

